### ISSUE TITLE
GAME.controller not working

### ISSUE THREAD

**Issue by dev-DTECH** [dev-DTECH/dev-DTECH.github.io#1]
https://github.com/dev-DTECH/dev-DTECH.github.io/blob/8cff3246daf978c24934e3e37de478e12bd5763b/engine/GAME.js#L67
this function is not working.When the user check ob.leftPressed it always remains false although a key is pressed.

**Comment by dev-abir** [comment]
I figured out the cause of this problem. In the GAME.js file in controller class execute console.log(left), you will get undefined, whereas if you call the same value from main.js, i.e., console.log(control.left), you will get 65. I am not much experienced in js, so....

I think you should use if(event.key == "a") (or make this.left = 'a'). This is much better than '65'

You should also check for ArrowUp, ArrowDown... events.
